### ISSUE TITLE
New Wipe config after load fails under Windows.

### ISSUE THREAD

**Issue by MrToast99** [turtlecoin/turtle-wallet-electron#102]
The new wipe config code fails to allow the wallet to create wconfig.txt, this causes "Unable to communicate with selected node" error. But if you first create a blank wconfig.txt then the wallet will load and delete wconfig.txt.

**Comment by rixombea** [comment]
works for me, tested both with clean profile and existing appdata (linux+windows)

**Comment by MrToast99** [comment]
Yes, i tried a different node. 

I just tried again with yesterdays compile and it's acting as i outlined above, This seems to be a Windows Server 2012R2 issue. Under Linux, Win10, and Win7 it all works fine.

**Comment by MrToast99** [comment]
It seems performing windows updates and rebooting solved the issue.
