### ISSUE TITLE
Walletshell - unable to communicate with selected node

### ISSUE THREAD

**Issue by kakhovsky** [turtlecoin/turtle-wallet-electron#108]
Unable to open wallet on any node, node appear to be fine. Internet in place.

**Comment by brondal** [comment]
I have the same problem

**Comment by spitzy83** [comment]
I'm having the exact same issue and I'm using the latest wallet shell V0.3.10 and I have tried all the nodes, even the ones that have fees.

It only worked once for me after trying 15 times using hashpool 

Internet works fine and no firewall is blocking the connection.

I have tried reimporting the wallet to a different filename using the mnemonic seed but although it imported fine, it still would not open on any node.

Would creating a custom local node help?

 I tried my local server IP:11898 but still same issue.

Can you please help?

**Comment by smithy1** [comment]
Does not work with its own node

**Comment by rixombea** [comment]
Hi, everyone, thanks for reporting...
Network currently under heavy load, daemon/nodes are probably got choked and having issues responding to rpc.  TurtleCoin core + walletshell updates are being prepared to help mitigate this issue.
If you are a public node operator or are running local daemon, it would be nice if you help testing new release candidate of TurtleCoin v0.13.0 here: https://github.com/turtlecoin/turtlecoin/issues/742

Some possible temporary solutions:
- if you have enough storage space, run your own local daemon, let it fully synchronized, then set your wallet to use it as your node (via 'add custom node'); OR
- keep retrying, keep switching node, wait few minutes/hours; OR
- build custom turtle-service binary:  
clone master repo, change the wait timeout value here: https://github.com/turtlecoin/turtlecoin/blob/68f25ef068ff605fa05270e72aee3c23654aa809/src/NodeRpcProxy/NodeRpcProxy.cpp#L161, put some high number (not too high, 120 seems OK), build/compile it, then replace the bundled turtle-service binary.

**Comment by smithy1** [comment]
![walletnode](https://user-images.githubusercontent.com/3511681/53398223-5f249500-39a9-11e9-8cc2-cd42dbdedc6d.JPG)

I cannot connect any node because I get this error.

**Comment by rixombea** [comment]
Please update to v0.3.11, if you still have a problem with node connection, try adjusting connection timeout value on the settings screen.

**Comment by tkoucinauci** [comment]
same problem with 0.3.11 and timeout set to max 120. Cannot connect with nodes.

**Comment by peeGLOW** [comment]
Yup...same problem

**Comment by radarlarry** [comment]
What are the developers doing to fix this?

**Comment by dxjmz** [comment]
Cant open my wallet also...

**Comment by Sajo8** [comment]
+1, wallet works w/ zedwallet but not w/ walletshell
