### ISSUE TITLE
Интуитивно понятный кошелёк

### ISSUE THREAD

**Issue by wolfimen** [turtlecoin/turtle-wallet-electron#115]
Сделайте простой и понятный GUI кошелёк. Постоянно просит файл какой-то. Пока кошель сделаешь, умереть можно, да и сидеть переключаться на переводчик гугл---не айс!!!
Ребята, вы же можете!!!

**Comment by brandonlehmann** [comment]
@wolfimen Would you be able to provide an English translation? I'm not sure that your message comes through very well via a translator:

```Make a simple and intuitive GUI wallet. Constantly asks for a file of some kind. As long as you do the purse, you can die, and you can sit on the google translator --- no ice !!!
Guys, you can !!!```

**Comment by stck** [comment]
@brandonlehmann, It seems that @wolfimen have a problem creating new wallet (btw wallet creation requires some files - what files @wolfimen didn't know). So it's more a feature-request for translations into Russian, or for some ux work to make wallet creation more intuitive.

**Comment by wolfimen** [comment]
Ребята, переводчик гугл в помощь с транслейт. Я пользуюсь компьютером и
интернетом, на уровне простого юзера. И у меня возникли проблемы с
установкой. Сначала назвать файл, затем указать место для его расположения.
После этого, для открытия кошелька пароль и снова место и название файла. Я
психанул и всё поудалял. Приношу свои извинения за резкость в
высказываниях. Мне кажется, что чем проще простому пользователю , тем
больше он будет этим пользоваться.

ср, 6 мар. 2019 г. в 19:26, Ivan Okunev <notifications@github.com>:

**Comment by rixombea** [comment]
@wolfimen please see: https://github.com/turtlecoin/turtle-wallet-electron/wiki/2.-Creating-New-Wallet
