### ISSUE TITLE
Fork for another coin

### ISSUE THREAD

**Issue by jwwi** [turtlecoin/turtle-wallet-electron#119]
hi
iam trying to forking this great piece of code, but the wallet can't connect to the node.
the wallet can only connect and synced when Turtlecoind is running local and i use the localhost:port as node.

where is my issue ?
my forking ports are: 

P2P_DEFAULT_PORT                              =  14114;
const int      RPC_DEFAULT_PORT           =  14115;
const int      SERVICE_DEFAULT_PORT    =  18114;

my node say's:
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:14114           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:14115         0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN

maybe i forgot something ....

**Comment by zpalmtree** [comment]
Did you launch your daemon with `--rpc-bind-ip 0.0.0.0`?
Check you can access it from outside the vps or whatever by doing something like
`curl your.node.ip:14115/getinfo`
(or open the url in a browser)

If you've done it correctly, you should see something like this: http://public.turtlenode.online:11898/getinfo

**Comment by jwwi** [comment]
Your the best !
--rpc-bind-ip 0.0.0.0  - is required ! after that i get the /getinfo about the blockchain
