### ISSUE TITLE
Any way to fix mixin counts?

### ISSUE THREAD

**Issue by guile124** [turtlecoin/turtle-wallet-electron#120]
There are any way to fix manually the mixin or allow mixin zero for transfers?
Thx.

**Comment by guile124** [comment]
I mean, is there a way to implement the CLI feature to optionally set mixin to 0 if transaction is too big in the GUI wallet?

**Comment by guile124** [comment]
@zpalmtree 🙏🐢

**Comment by zpalmtree** [comment]
I do not maintain this code, so am unsure. I believe the RPC may not return enough information to determine if the transaction fail was due to being unable to get outputs.

**Comment by brandonlehmann** [comment]
If you request random outputs from the daemon and it doesn't return enough outputs that's a sure fire way to know that the transaction will fail. The only way to know is to ask.

**Comment by zpalmtree** [comment]
Sure, but turtle-service is doing the asking. wallet-api does return this as a specific error code though :^)

**Comment by guile124** [comment]
@zpalmtree @brandonlehmann 
And if I run a custom node locally (127.0.0.1...) and launch manually the daemon? 
Fixin de config default mixin value at zero in ws_config.js?
Should be it work? Or I'm saying nonsense?

**Comment by zpalmtree** [comment]
The default mixin value via config is not used, you need to set DEFAULT_MIXIN in your mixin limits in CryptoNoteConfig, and recompile.

**Comment by guile124** [comment]
@zpalmtree I know but I have minimum of zero and maximum of 3, 
if I set default to zero it will be static at zero, and I think it is not the best way, or im wrong?
In CLI (walletconfig.h) I have set mixinZeroDisabled = false; and it solve the bug when the users try to send big amounts, it would be cool to can set it in a GUI wallet.

**Comment by rixombea** [comment]
include the `anonimity` parameter here:
https://github.com/turtlecoin/turtle-wallet-electron/blob/11122f8669e9ac07f47cc23c2879dfba01d5172d/src/js/ws_api.js#L202-L205

then add "mixin" field to the ui form -- custom mixin params was used in older version, check older release/commits, not sure which one

**Comment by zpalmtree** [comment]
@guile124 You are correct, @rixombea's suggestion is the best way to proceed if you want to retain anonymity where possible. If you want to automatically set 0 mixin, you'll have to check the error code / message returned from the wallet, and figure out what to do from there.

It's not going to be a priority to be implemented in the turtle version, as we have a static mixin, so would just complicate the codebase for no benefit.

**Comment by guile124** [comment]
I will try,
Thanks for your support guys!
