### ISSUE TITLE
Improve wallet import/create filename picker

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-electron#128]
A few people find the choosing a filename step a little confusing. Whether this is because they're not great at english and don't understand the description, or some other reason, they often believe they need an existing file, rather than having to create one.

I propose the input is changed to two forms.

The first, is for entering the wallet name. Have it default to something, for ease of use.
The second, is for choosing the directory to store the wallet in. Default to the documents directory on windows, home directory/cwd on linux?

---

Pick a name for your wallet
[ mywallet.twl ]
Pick the folder to save your wallet in
[ C:/Documents ]

---

Hopefully that description is clear. Thanks!

**Comment by rixombea** [comment]
Earlier version used to have 2 separate fields for wallet filename & directory, just like you described. But later, (iirc) there are peoples complain/requesting to merge the field.

Still not sure if I should revert it, but in the meantime, this @old-greywolf's video guide may help those users: https://github.com/turtlecoin/turtle-wallet-electron/wiki/2.-Creating-New-Wallet 

(Also, link to the whole [User Guide Wiki](https://github.com/turtlecoin/turtle-wallet-electron/wiki) is there on the main page)
