### ISSUE TITLE
Wallet disconnects from daemon.

### ISSUE THREAD

**Issue by projectpixel1080** [turtlecoin/turtle-wallet-electron#136]
Hey Guys! 
We recently forked TRTL and everything works fine with Zedwallet.  The electron wallet does not though. It briefly connects to a node then says "Unable to communicate with the selected node, please try again or switch to another node address".  We currently have 2 seed nodes, each on different VPS providers.  Both running the same OS and no issues with the CLI wallet.

**Comment by blockinator** [comment]
Start your coin's daemon like so:
`./Coind --rpc-bind-ip 0.0.0.0`

Then your wallet can connect remotely.

**Comment by blockinator** [comment]
> Hey Guys!
> We recently forked TRTL and everything works fine with Zedwallet. The electron wallet does not though. It briefly connects to a node then says "Unable to communicate with the selected node, please try again or switch to another node address". We currently have 2 seed nodes, each on different VPS providers. Both running the same OS and no issues with the CLI wallet.

Start your coin's daemon like so:
`./Coind --rpc-bind-ip 0.0.0.0`

Then your wallet can connect remotely.
