### ISSUE TITLE
Add a 'Reveal' button / hint to individual private keys menu

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-electron#16]
I'm an idiot so after I clicked the 'Private Keys' button I didn't realise why the fields were blank - took me about 10 seconds to notice the 'Reveal' button - maybe add a button in each input, or a hint saying something like:

'Click the reveal button to show your private keys'

Also, maybe my confusion was slightly amplified by the button shading - They blend in with the background reasonably well, and look somewhat like unusable 'faded out' buttons. They pop out when you hover over them, but it might be a better experience if they have that style by default.

**Comment by zpalmtree** [comment]
The buttons are easily noticeable in dark mode, btw. Dark mode is cool. :sunglasses:

**Comment by rixombea** [comment]
@zpalmtree is it good enough?

![ss_20180925_095040](https://user-images.githubusercontent.com/42405930/45990130-2ab15380-c06e-11e8-847b-f3ef54da40d4.png)

**Comment by zpalmtree** [comment]
Looks good :+1:
