### ISSUE TITLE
Install workflow is a tad confusing

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-electron#27]
The WalletShell setup launches the program afterwards, so if you were not aware it creates shortcuts you may 'install' it every time. Doesn't really have any adverse effects that I noticed...

**Comment by rixombea** [comment]
Maybe add something to the install-guide/readme to make it clear, OR use guided setup mode instead of one-click setup? Any suggestions for a better/non-confusing solution?

**Comment by zpalmtree** [comment]
Not sure really I'm afraid...
