### ISSUE TITLE
Can't write into fields on Mac OS

### ISSUE THREAD

**Issue by furiousteam** [turtlecoin/turtle-wallet-electron#43]
Hello,

i'm about to test the [WalletShell with the TurtleCoin v0.10.0-RC2](https://github.com/turtlecoin/turtlecoin/issues/601) so i can send you full report on Mac OS.

My problem is once i start the WalletShell i can not type anything inside the fields. i can only copy/paste but i can not type content inside each form. So i need to have a txt file near by to be able to copy and paste all the commands to test.

Do you have any tip for this please ?

Thank you.

**Comment by rixombea** [comment]
@furiousteam is this one still reproducible?

if so, can you run it in debug mode: `npm run dev`, watch the output and report me back if there are errors

**Comment by rixombea** [comment]
So, in summary:
- input fields are works/function normally (so I can close this issue)
- node list selection field needs improvement, will replace it with simple select field on the next revision

thanks @old-greywolf @furiousteam for taking your time!
