### ISSUE TITLE
Mnemonic seed box says "click reveal to show" after I click reveal and the other boxes are populated

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtle-wallet-electron#72]
So my wallet is old enough such that it doesn't support/have a mnemonic seed, so I have to backup my private keys. 
The problem is, after I click reveal on the private keys menu, the box for the mnemonic seed still says "click to reveal" after the keys' boxes have been populated; this should maybe instead say "seed not available for this wallet" or something of the sort to show that this wallet doesn't support/have a seed.

**Comment by rixombea** [comment]
fixed with #74 -- thanks @Sajo8 !
