### ISSUE TITLE
remote node list looks bad

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtle-wallet-electron#75]
So:
1) the font is bad! It's super hard to read and I have to squint my eyes to see what's what
2) the list looks messy. now i know the list of the nodes should be randomized each time ( i think it is? either this or someother wallet idk) but the names and the pos. of the fee is variable and that's a tad bit annoying. is it possible for the fee to be aligned at the end of the thing? when we mouse over it it highlights the selection so we know which node's fee we're loooking at. example:
![goodlist](https://user-images.githubusercontent.com/33220209/51648639-2c861780-1f79-11e9-9a3c-fa570c0c39c1.png) (just moved the stuff in 2 min in photoshop)

**Comment by rixombea** [comment]
@Sajo8  please check #77 and let me know if it's still hurts your eyes :laughing: 

![ss_20190124_135704](https://user-images.githubusercontent.com/42405930/51682862-59b9e080-1fe0-11e9-9d6e-a93d546d25b2.png)

**Comment by Sajo8** [comment]
ah sweet sweet eyecandy
