### ISSUE TITLE
no way to remove custom remote nodes

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtle-wallet-electron#76]
title basically. maybe change "add custom node" to "manage custom nodes" and show the normal input box as there is now but also let you change/remove existing custom nodes.

**Comment by rixombea** [comment]
implemented in #77 -- please test it whenever you have time

![ss_20190124_204557](https://user-images.githubusercontent.com/42405930/51682982-aef5f200-1fe0-11e9-80ba-abbaf8c83ff9.png)
