### ISSUE TITLE
Can't press open wallet on the Walletshell 

### ISSUE THREAD

**Issue by turtlepleb** [turtlecoin/turtle-wallet-electron#86]
Dear programming turtles

I can't press open wallet on the WalletShell v0.3.9. 
When I look at the processes I only see 3 processes running:
![image](https://user-images.githubusercontent.com/47226857/52083041-b0a25580-259e-11e9-84e3-478b54fc022a.png)

What did i do, I deleted version 0.3.8 and installed v0.3.9.
OS: Windows 10 version 1803

Greetings
Turtlepleb

**Comment by turtlepleb** [comment]
Closed all 3 processes, started the wallet again and I'm still unable to open the wallet. Always the same 3 processes will start. I also uninstalled V0.3.9 and installed it again. I didn't reboot yet(because I'm lazy). But I will now.

**Comment by turtlepleb** [comment]
Deleted the folder WalletShell under %appdata% and now I can open my wallet again.

**Comment by RocksteadyTC** [comment]
Great!

**Comment by zpalmtree** [comment]
I don't think is a resolution to the issue. Sounds like the wallet is failing to upgrade settings correctly. Requesting reopen.

**Comment by rixombea** [comment]
fixed with #87 -- quick fix release soon, 

@turtlepleb thanks for reporting
