### ISSUE TITLE
Feature request rescan wallet

### ISSUE THREAD

**Issue by therealholger** [turtlecoin/turtle-wallet-electron#91]
I am missing a rescan wallet option
Best would be  with optional rescan from height

**Comment by rixombea** [comment]
rescan from height for currently opened wallet is not (yet) implemented, but you can re-import your wallet and specify the scan height while doing that.

maybe in future revisions, PR are also welcome :/

**Comment by Sajo8** [comment]
>looks at doing a PR
>css

imout

**Comment by rixombea** [comment]
@therealholger implemented in #101 -- Thanks!
