### ISSUE TITLE
Make node list refresh faster

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtle-wallet-electron#94]
Takes too long, here's what I'm thinkig:

1. grab the list
2. let the ppl click and see the list
3. in the bg, asynchronously ping each node to check if their up. meanwhile, display some grey thing to indicate unknown status. *the person should still be able to open a node even if the status isn't verified when in this step*.
4. update the list as you get responses, *as the list is open*. onlines are shown as green, unknown as green, and offline as red. if the person closes and re-opens the list, it shown only the active node and the unknown ones, as it does rn.

**Comment by rixombea** [comment]
commit 22ba3a7d6fd7dbe79f2775497a2426e45b15cae2 revert node check behavior: will only performed once a day, but now allow user to manually refresh the list. Also will check network connectivity before performing update.

**Comment by rixombea** [comment]
fixed w/ #93
