### ISSUE TITLE
wconfig.txt fix suggestion

### ISSUE THREAD

**Issue by MrToast99** [turtlecoin/turtle-wallet-electron#98]
In testing this option works fine. Been running it for weeks.

Thoughts?

updates to ws_session.js

remove line> const WALLET_CFG = path.join(remote.app.getPath('userData'), 'wconfig.txt');
update > walletConfig: '',

**Comment by rixombea** [comment]
hi, thanks for your suggestion.

But, I'm not sure what are you trying to solve. By removing that, it will not use tmp config and use cmd switch/args for passing parameters, which is basically doing the same thing (see: #84)

**Comment by MrToast99** [comment]
Ah, now I understand what it's doing. 

my bad.

**Comment by MrToast99** [comment]
What about:

const WALLET_CFG = path.join(remote.app.getPath('userData'), crypto.randomBytes(16).toString('hex'));

and somehow Obfuscate the contents like the Adressbook? I know the key would be in the config.
