### ISSUE TITLE
Installing over previous directory will delete unrelated directories

### ISSUE THREAD

**Issue by Virosa** [turtlecoin/turtle-wallet-electron#99]
For instance making a walletbak folder inside the installation folder and putting your wallet there will result in deletion of your wallet. 

The software seem to wipe the whole directory rather than contain a list of its dependents.

**Comment by rixombea** [comment]
@Virosa thanks for reporting!

[nsis](https://nsis.sourceforge.io/) used for windows installer. Install directory will be wiped during upgrade, but files inside appdata are safe. 
I'm not really familiar w/ win environment, not sure if the behaviour can be changed or not. Also I don't want to mess with the windows installer, so my suggestion is, don't put anything inside Program/Installation directory.
